name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        uses: TartanLlama/actions-eleventy@v1.2
        with:
          install_dependencies: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.10.0
        env:
          PUBLISH_DIR: _site
          PUBLISH_BRANCH: gh-pages
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        with:
          forceOrphan: true
